name: VitalKeepExp
version: @version@
main: com.tamrielnetwork.vitalkeepexp.VitalKeepExp
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to keep exp on death.